### ISSUE TITLE
about the utility

### ISSUE THREAD

**Issue by yangzhangok** [xiwan/LLM-Game-Agents#1]
Thanks for your contribution! I have tried to deploy your project on my personal computer.( windows 11)
I have git the project and could run the Entry.py.
However, when I open the localhost:8000 or the http://10.136.7.157:8000, I found there was just a "hello world" on the screen. 
And the output is like:

```
Command line arguments: ['d:/agent/LLM-Game-Agents/WereWolf/Entry.py']
Round value: 50
Queue size: 50
10/03/2024 04:09:32 PM WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.136.7.157:8000
10/03/2024 04:09:32 PM Press CTRL+C to quit
```

Do you know what should I do next?

**Comment by yangzhangok** [comment]
Sorry for my interruption! I have got to know some knowledge about the web server and the connection between it and the application and found that I should firstly get familiar with some usage of the flask.

**Comment by shannany0606** [comment]
> Sorry for my interruption! I have got to know some knowledge about the web server and the connection between it and the application and found that I should firstly get familiar with some usage of the flask.

Do you know how to start the game? I met the same error as yours, and do not know what to do next.
